#... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase
    spec:
      containers:
        - name: app
          image: ydulanjani/coinbase:latest
          ports:
            - containerPort: 3030
          imagePullPolicy: Always
          command: ["/bin/sh", "-ec", "sleep 1000"]
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: coinbase2
spec:
  selector:
    app: coinbase
  ports:
    - port: 3030
      targetPort: 3030
  type: LoadBalancer